USE Company;
CREATE TABLE EMPLOYEE (
    FNAME VARCHAR(20),
    MINIT CHAR(1),
    LNAME VARCHAR(20),
    SSN INT PRIMARY KEY,
    BDATE DATE,
    ADDRESS VARCHAR(50),
    SEX CHAR(1),
    SALARY DECIMAL(9,3),
    SUPERSSN INT,
    DNO INT
);
CREATE TABLE DEPARTMENT (
    DNAME VARCHAR(30),
    DNUMBER INT PRIMARY KEY,
    MGRSSN INT,
    MGRSTARTDATE DATE
);
CREATE TABLE DEPT_LOCATIONS (
    DNUMBER INT,
    DLOCATION VARCHAR(30),
    PRIMARY KEY (DNUMBER , DLOCATION)
);
CREATE TABLE PROJECT (
    PNAME VARCHAR(30),
    PNUMBER INT PRIMARY KEY,
    PLOCATION VARCHAR(30),
    DNUM INT
);
CREATE TABLE WORKS_ON (
    ESSN INT,
    PNO INT,
    HOURS DECIMAL(4,1),
    PRIMARY KEY (ESSN , PNO)
);

CREATE TABLE DEPENDENT (
    ESSN INT,
    DEPENDENT_NAME VARCHAR(30),
    SEX CHAR(1),
    BDATE DATE,
    RELATIONSHIP VARCHAR(20),
    PRIMARY KEY (ESSN , DEPENDENT_NAME)
);
ALTER TABLE EMPLOYEE
ADD FOREIGN KEY (DNO)
REFERENCES DEPARTMENT(DNUMBER);

ALTER TABLE EMPLOYEE
ADD FOREIGN KEY (SUPERSSN)
REFERENCES EMPLOYEE(SSN);

ALTER TABLE DEPARTMENT
ADD FOREIGN KEY (MGRSSN)
REFERENCES EMPLOYEE(SSN);

ALTER TABLE DEPT_LOCATIONS
ADD FOREIGN KEY (DNUMBER)
REFERENCES DEPARTMENT(DNUMBER);

ALTER TABLE PROJECT
ADD FOREIGN KEY (DNUM)
REFERENCES DEPARTMENT(DNUMBER);

ALTER TABLE WORKS_ON
ADD FOREIGN KEY (ESSN)
REFERENCES EMPLOYEE(SSN);

ALTER TABLE WORKS_ON
ADD FOREIGN KEY (PNO)
REFERENCES PROJECT(PNUMBER);

ALTER TABLE DEPENDENT
ADD FOREIGN KEY (ESSN)
REFERENCES EMPLOYEE(SSN);

INSERT INTO DEPARTMENT VALUES ('IT',1,NULL,'2022-01-01');
INSERT INTO DEPARTMENT VALUES ('HR',2,NULL,'2022-02-01');

INSERT INTO EMPLOYEE VALUES
('Mhmd','A','Ali',111,'1995-05-05','Cairo','M',5000,NULL,1);

INSERT INTO EMPLOYEE VALUES
('Sara','M','Hassan',222,'1998-3-30','Giza','F',4500,111,2);

UPDATE DEPARTMENT SET MGRSSN = 111 WHERE DNUMBER = 1;
UPDATE DEPARTMENT SET MGRSSN = 222 WHERE DNUMBER = 2;

INSERT INTO PROJECT VALUES ('Website',10,'Cairo',1);
INSERT INTO PROJECT VALUES ('App',20,'Giza',2);

INSERT INTO WORKS_ON VALUES (111,10,20);
INSERT INTO WORKS_ON VALUES (222,20,15);

INSERT INTO DEPENDENT VALUES (111,'Omar','M','2015-01-01','Son');
INSERT INTO DEPENDENT VALUES (222,'Lina','F','2018-02-02','Daughter');

INSERT INTO DEPT_LOCATIONS VALUES (1,'Cairo');
INSERT INTO DEPT_LOCATIONS VALUES (2,'Giza');


--Display all the employees Data
SELECT *
FROM EMPLOYEE;

--Display the employee First name, last name, Salary and Department number
SELECT Fname , Lname , Salary , Dno
FROM EMPLOYEE;


/*Display all the projects names, locations and the department which is responsible
about i*/
SELECT P.Pname , P.Plocation , D.Dname
FROM PROJECT P
JOIN DEPARTMENT D
ON P.Dnum = D.Dnumber;

/*Display each employee full name and his annual commission in an ANNUAL COMM column
(alias).*/

SELECT 
Fname + ' ' + Lname AS Full_Name,
Salary * 12 * 0.10 AS [ANNUAL COMM]
FROM EMPLOYEE;

--Display the employees Id, name who earns more than 1000 LE monthly
SELECT SSN , Fname , Lname
FROM EMPLOYEE
WHERE Salary > 1000;

--Display the employees Id, name who earns more than 10000 LE annually
SELECT SSN , Fname , Lname
FROM EMPLOYEE
WHERE Salary * 12 > 10000;

--Display the names and salaries of the female employees
SELECT Fname , Lname , Salary
FROM EMPLOYEE
WHERE Sex = 'F';

/*Display each department id, name which managed by a manager with id equals
968574*/
SELECT Dnumber , Dname
FROM DEPARTMENT
WHERE MgrSSN = 968574;

/*Dispaly the ids, names and locations of the pojects which controled with
department 10.*/
SELECT Pnumber , Pname , Plocation , Dnum
FROM PROJECT
WHERE Dnum = 10;


INSERT INTO EMPLOYEE (FNAME, MINIT, LNAME, SSN, BDATE, ADDRESS, SEX, SALARY, SUPERSSN, DNO)
VALUES ('Ali', 'A', 'Mohamed', 968574, '1980-01-01', 'Cairo', 'M', 6000, NULL, NULL);

INSERT INTO DEPARTMENT (DNAME, DNUMBER, MGRSSN, MGRSTARTDATE)
VALUES ('New Department', 10, 968574, '2024-02-10');

INSERT INTO PROJECT (PNAME, PNUMBER, PLOCATION, DNUM)
VALUES 
('Project A', 30, 'Cairo', 10),
('Project B', 40, 'Giza', 10);

SELECT Pnumber , Pname , Plocation , Dnum
FROM PROJECT
WHERE Dnum = 10;


SELECT Dnumber , Dname
FROM DEPARTMENT
WHERE MgrSSN = 968574;

